# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18m3JMKqDXp5FqBfS3SbS5eD6UAyemBEp
"""

import numpy as np

a = np.array([2,5,6], dtype =float)
a

b = np.arange(10,20)
print(np.size(b))

c = b.reshape((2,5))
c

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(type(c))

a = np.zeros((3,4), dtype = float)
a

a = np.full((2,2) ,6)
a

a = np.zeros((3,4), dtype = float)
a

d = np.random.randn(3,4)
 d

d1 = np.random.randint(10,100, 10)
d1

c

print(c[:,3])

print(c[1,:])

a = np.array([2,4,5])
b = a
b[1]=3
print(b)

print(a)

a = np.array([2,4,5])
b = a.copy()
b[1]=3
print(b)
print(a)

a = np.ones((2,3), dtype= int)
b = np.full((3,2),5)

print(a+b)

print(a*b)

print(np.dot(a,b))

print(a@b)

d1 = np.random.randint(10,100, 20)
d1

d1 =d1.reshape(4,5)
d1

print(np.min(d1))
print(np.argmin(d1))

print(np.min(d1,axis = 1))

print(np.sum(d1,axis = 0))

# vertical stacking
a = ([2,4,6],[5,3,8])
b = ([2,7,6])
print(a)
print(b)

s= np.vstack([a,b])
s

a = ([2,4,6],[5,3,8])
b = ([2,7],[5,6])
print(a)
print(b)

s= np.hstack([a,b])
s

print(s.shape)

d = np.genfromtxt("data.txt",delimiter= ",")
d = d.astype("int")
d

print(d.shape)

d > 50

np.argwhere(d>50)

d [:,0:6]

# any , all
np.any(d >50 , axis=0)

d[:,~ np.any(d >50 , axis=0)]